# Generated by Django 5.2 on 2025-05-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='image',
        ),
    ]
