# Generated by Django 4.2 on 2025-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_description_exam_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images'),
        ),
    ]
